node main.js addArtist "canserbero" "Venezuela"
node main.js addArtist "gnr" "USA"
node main.js addArtist "bon jovi" "USA"
node main.js addArtist "tiago" "Argentina"
node main.js addArtist "pearl jam" "USA"